# ── Server ────────────────────────────────────────────────────────────────────
server.port=${PORT:8080}

# ── DataSource ────────────────────────────────────────────────────────────────
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/eventflow}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# ── JPA ───────────────────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.open-in-view=false

# ── Flyway ────────────────────────────────────────────────────────────────────
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ── JWT ───────────────────────────────────────────────────────────────────────
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# ── Resend Email ──────────────────────────────────────────────────────────────
app.resend.api-key=${RESEND_API_KEY:re_CZPgtXJB_4Sn54b2eLAYKYB37ULkBT31w}
app.mail.from=${MAIL_FROM:onboarding@resend.dev}
app.base-url=${BASE_URL:http://localhost:8080}

# ── Actuator ──────────────────────────────────────────────────────────────────
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

# ── SpringDoc / Swagger ───────────────────────────────────────────────────────
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# ── Logging ───────────────────────────────────────────────────────────────────
logging.level.com.ctbe.eventflow=INFO

#  ── cros ───────────────────────────────────────────────────────────────────
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}